let firstName = "Cengiz";
let lastName = "Türkeş";
let country = "Türkiye";
let city = "Muğla";
let age = 102;
let isMarried = false;
const gravity = 9.81;
const PI = 3.14;
let name = "Cengiz",
  job = "Engineer",
  live = "Turkey";
